export const products = [
    {
        id: 1,
        brand: "Levi's",
        type: "RELAXED FIT TEE UNISEX",
        frontImg: "/img/1.webp",
        backImg: "/img/1b.webp",
        eco: "Sostenibilità",
        discount: 50,
        fullPrice: 29.99,
    },
    {
        id: 2,
        brand: "Guess",
        type: "ROSES TEE",
        frontImg: "/img/2.webp",
        backImg: "/img/2b.webp",
        eco: null,
        discount: 30,
        fullPrice: 29.99,
    },
    {
        id: 3,
        brand: "Come Zucchero Filato",
        type: "VOGLIA DI COLORI PASTELLO",
        frontImg: "/img/3.webp",
        backImg: "/img/3b.webp",
        eco: null,
        discount: 30,
        fullPrice: 184.99,

    },
    {
        id: 4,
        brand: "Levi's",
        type: "TEE UNISEX",
        frontImg: "/img/4.webp",
        backImg: "/img/4b.webp",
        eco: "Sostenibilità",
        discount: 50,
        fullPrice: 29.99,
    },
    {
        id: 5,
        brand: "Maya Deluxe",
        type: "STRIPE BODICE",
        frontImg: "/img/5.webp",
        backImg: "/img/5b.webp",
        eco: null,
        discount: null,
        fullPrice: 99.99,
    },
    {
        id: 6,
        brand: "Espirit",
        type: "MAGLIONE - BLACK",
        frontImg: "/img/6.webp",
        backImg: "/img/6b.webp",
        eco: "Sostenibilità",
        discount: null,
        fullPrice: 99.99,
    },
]


